id: IC994E435
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T16:10:32+00:00'
last_modified: '2022-06-08T09:37:49.208338+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG6140
  title: མངོན་པ་གོང་མ་དང་འབྲེལ་བའི་སེམས་ཁམས་རིག་པའི་གཞུང་ལུགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '8261':
      image_group_id: I1KG6207
      title: ''
      total_pages: 436
      order: 1
      base_file: 8261.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
