id: IC994E435
legacy_id: P006916
ocr_import_info:
  bdrc_scan_id: W1KG6140
  source: bdrc
  ocr_info:
    timestamp: '2022-03-15T10:04:08'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T17:43:16.421614+00:00'
last_modified: 2022-09-01 01:43:34.263972
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG6140
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG6140
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མངོན་པ་གོང་མ་དང་འབྲེལ་བའི་སེམས་ཁམས་རིག་པའི་གཞུང་ལུགས།
  author: རེད་མདའ་བ་གཞོན་ནུ་བློ་གྲོས།
statistics:
  ocr_word_mean_confidence_index: 0.9488059758758225
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG6207:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG6207
      total_pages: 436
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG6207.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9488059758758225
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
