id: P006916
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG6140
  title: མངོན་པ་གོང་མ་དང་འབྲེལ་བའི་སེམས་ཁམས་རིག་པའི་གཞུང་ལུགས།
  author: ''
  volumes:
    fe74534054d04cbdbff45cf4315f7a2a:
      image_group_id: I1KG6207
      title: ''
      volume_number: 1
      total_pages: 436
      base_file: v001.txt
